# Creates a GitHub release when a release candidate PR is merged
name: Finalize Release ⛵

on:
  pull_request:
    types:
      - closed

jobs:
  create-release:
    # Only run when a release candidate PR is merged (not just closed)
    if: >
      github.event.pull_request.merged == true &&
      startsWith(github.event.pull_request.title, 'Release Candidate:')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history for changelog

      - name: Extract Version
        id: extract_version
        run: |
          # Extract version from PR title (format: "Release Candidate: v1.1.0")
          VERSION=$(echo "${{ github.event.pull_request.title }}" | sed -E 's/Release Candidate: v([0-9]+\.[0-9]+\.[0-9]+).*/\1/')
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Verify Changelog
        run: |
          if [ ! -f "CHANGELOG.md" ]; then
            echo "Error: CHANGELOG.md not found"
            exit 1
          fi

          # Changed from "## Release v" to "## v"
          if ! grep -q "## v${{ env.VERSION }}" CHANGELOG.md; then
            echo "Error: v${{ env.VERSION }} section not found in CHANGELOG.md"
            exit 1
          fi

      - name: Extract current version from changelog
        id: extract_changelog
        run: |
          # Create a temporary file to store the current version's changelog
          touch current_version_changelog.md

          # Extract the section for the current version only
          awk -v version="## v${{ env.VERSION }}" '
          BEGIN { found=0; }
          $0 ~ version { found=1; print; next; }
          /^## v[0-9]+\.[0-9]+\.[0-9]+/ { if (found) exit; }
          found == 1 { print; }
          ' CHANGELOG.md > current_version_changelog.md

          # Debug: check the extracted content
          echo "Extracted changelog content:"
          cat current_version_changelog.md

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ env.VERSION }}"
          name: "v${{ env.VERSION }}"
          body_path: current_version_changelog.md
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Delete the release candidate branch
          git push origin --delete "${{ github.event.pull_request.head.ref }}" || true
